### PR TITLE
Jocky error on card page

### PR DESCRIPTION
**Pull request by eluxen**
We got the following error:

     Error: TypeError: undefined is not a function (evaluating 'Jockey.targetWindow.postMessage({type:type,envelope:envelope},Jockey.targetDomain)') in file:///private/var/mobile/Containers/Bundle/Application/87B8DE67-5F02-4D47-8AE1-8310AAE847D2/Foodiebag.app/www/lib/klarna/klarna-on-demand.min.js at line 7

My _guess_ is that we had a race condition - we got a message after  closing the iframe.
So now, we turn off the jockey listener before closing the frame

### CODE REVIEW

**Comment by grozen** [comment]
@eluxen since I've changed quite a few things recently, would you mind merging master into this so that we can benefit from the terrificness?

**Comment by eluxen** [comment]
@grozen done

**Comment by eluxen** [comment]
can I merge?

**Comment by grozen** [comment]
@eluxen Travis says you can, so go right ahead :)
It would also be a great opportunity for you to deploy this new version to NPM.

**Pull request merged**
